{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.137.1102.0 (24.10)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Spotify Dataset\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "es-MX",
    "cultures": [
      {
        "name": "es-MX",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "es-CO",
    "tables": [
      {
        "name": "Spotify Dataset",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "track_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c87268f2-1d7f-41e2-aef2-ad0d631dc094",
            "sourceColumn": "track_name",
            "summarizeBy": "none"
          },
          {
            "name": "artist(s)_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "804174d1-99cb-438f-b7f1-e39ed862e841",
            "sourceColumn": "artist(s)_name",
            "summarizeBy": "none"
          },
          {
            "name": "artist_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "977b10fb-1baa-4b68-b503-ea20d1b58404",
            "sourceColumn": "artist_count",
            "summarizeBy": "sum"
          },
          {
            "name": "released_year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "004f7cd4-ca86-4b26-9fd6-23220c7af8d0",
            "sourceColumn": "released_year",
            "summarizeBy": "sum"
          },
          {
            "name": "released_month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "47829e66-ffdb-4437-a2b0-ec8d10dae89b",
            "sourceColumn": "released_month",
            "summarizeBy": "sum"
          },
          {
            "name": "released_day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "037b5a3f-2fb5-4f74-8102-1a10f593bd65",
            "sourceColumn": "released_day",
            "summarizeBy": "sum"
          },
          {
            "name": "in_spotify_playlists",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "74dc4c1f-b61e-4f4a-98b9-db502db9f25c",
            "sourceColumn": "in_spotify_playlists",
            "summarizeBy": "sum"
          },
          {
            "name": "in_spotify_charts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "51969afa-337b-4a0d-be6d-d804278546e7",
            "sourceColumn": "in_spotify_charts",
            "summarizeBy": "sum"
          },
          {
            "name": "streams",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1e122ec8-af30-466b-bdfc-576db2855b63",
            "sourceColumn": "streams",
            "summarizeBy": "sum"
          },
          {
            "name": "in_apple_playlists",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "27a99ff0-279c-42b7-b3ea-15380fd2b988",
            "sourceColumn": "in_apple_playlists",
            "summarizeBy": "sum"
          },
          {
            "name": "in_apple_charts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b9b935b4-7c63-48ce-b4ef-098a0f761131",
            "sourceColumn": "in_apple_charts",
            "summarizeBy": "sum"
          },
          {
            "name": "in_deezer_playlists",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f1b9e259-9aa9-4a4f-8875-96109b1813dd",
            "sourceColumn": "in_deezer_playlists",
            "summarizeBy": "sum"
          },
          {
            "name": "in_deezer_charts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e67f8bd2-573f-4d16-8979-9626babc4f35",
            "sourceColumn": "in_deezer_charts",
            "summarizeBy": "sum"
          },
          {
            "name": "in_shazam_charts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2fc9f6ec-f6e0-404b-8de4-4629e022edd7",
            "sourceColumn": "in_shazam_charts",
            "summarizeBy": "sum"
          },
          {
            "name": "bpm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "44d72102-64e5-428a-b86f-42acc808c267",
            "sourceColumn": "bpm",
            "summarizeBy": "sum"
          },
          {
            "name": "key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8e547158-1c15-4c9d-8cd7-abb6222c1660",
            "sourceColumn": "key",
            "summarizeBy": "none"
          },
          {
            "name": "mode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a2410e03-76b9-4030-8227-9d3acaf07d0c",
            "sourceColumn": "mode",
            "summarizeBy": "none"
          },
          {
            "name": "danceability_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "14973286-9868-46bc-b4e0-4836a843dd63",
            "sourceColumn": "danceability_%",
            "summarizeBy": "sum"
          },
          {
            "name": "valence_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8e96c834-3e7a-4362-ab33-f8de37b6c49f",
            "sourceColumn": "valence_%",
            "summarizeBy": "sum"
          },
          {
            "name": "energy_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "abcc2a19-92ff-45b4-99ee-e6dbf55ea717",
            "sourceColumn": "energy_%",
            "summarizeBy": "sum"
          },
          {
            "name": "acousticness_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f628f090-6118-4791-be33-7975cb40aae5",
            "sourceColumn": "acousticness_%",
            "summarizeBy": "sum"
          },
          {
            "name": "instrumentalness_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b18c2adc-3d65-4245-8a35-1cf1af5de328",
            "sourceColumn": "instrumentalness_%",
            "summarizeBy": "sum"
          },
          {
            "name": "liveness_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f3a9b352-b08d-4073-9dbc-7687d1225adf",
            "sourceColumn": "liveness_%",
            "summarizeBy": "sum"
          },
          {
            "name": "speechiness_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3a27bf5f-2da9-4f7b-b570-1d80132055a9",
            "sourceColumn": "speechiness_%",
            "summarizeBy": "sum"
          },
          {
            "name": "cover_url",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8bb05890-8d6a-4f96-873f-6e03eb48b77f",
            "sourceColumn": "cover_url",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "22dbb203-684c-4745-b43e-e93a0b2aecd0",
        "partitions": [
          {
            "name": "Spotify Dataset",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Excel.Workbook(File.Contents(\"C:\\Users\\juanrios\\Desktop\\Onyx Data DataDNA Datatset Challenge - Spotify Most Streamed Songs 2023 Dataset - October 2023.xlsx\"), null, true),",
                "    #\"Spotify Dataset_Sheet\" = Origen{[Item=\"Spotify Dataset\",Kind=\"Sheet\"]}[Data],",
                "    #\"Encabezados promovidos\" = Table.PromoteHeaders(#\"Spotify Dataset_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Encabezados promovidos\",{{\"track_name\", type any}, {\"artist(s)_name\", type text}, {\"artist_count\", Int64.Type}, {\"released_year\", Int64.Type}, {\"released_month\", Int64.Type}, {\"released_day\", Int64.Type}, {\"in_spotify_playlists\", Int64.Type}, {\"in_spotify_charts\", Int64.Type}, {\"streams\", Int64.Type}, {\"in_apple_playlists\", Int64.Type}, {\"in_apple_charts\", Int64.Type}, {\"in_deezer_playlists\", Int64.Type}, {\"in_deezer_charts\", Int64.Type}, {\"in_shazam_charts\", Int64.Type}, {\"bpm\", Int64.Type}, {\"key\", type text}, {\"mode\", type text}, {\"danceability_%\", Int64.Type}, {\"valence_%\", Int64.Type}, {\"energy_%\", Int64.Type}, {\"acousticness_%\", Int64.Type}, {\"instrumentalness_%\", Int64.Type}, {\"liveness_%\", Int64.Type}, {\"speechiness_%\", Int64.Type}, {\"cover_url\", type text}})",
                "in",
                "    #\"Tipo cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}